import React from "react";
import type { Metadata } from "next";
import "../../globals.css";
import { Footer, Header } from "@/shared/components/";
import { cookies } from "next/headers";
import { AdminHeader, AdminSidebar } from "@/shared/components/admin";

export const metadata: Metadata = {
  title: "Smoky Moon | Админка",
  description: "Generated by create next app",
  icons: "../favicon.ico",
  manifest: "../icons/site.webmanifest",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const acceptedCookies = cookieStore.get("acceptedCookies");
  const adult = cookieStore.get("adult");
  return (
    <main className="min-h-screen bg-background">
      <AdminHeader />
      <AdminSidebar />
      {children}
    </main>
  );
}
