import React from "react";
import type { Metadata } from "next";
import "../globals.css";
import { Footer, Header } from "@/shared/components/";

export const metadata: Metadata = {
  title: "Smoky Moon",
  description: "Generated by create next app",
  icons: "../favicon.ico",
  manifest: "../icons/site.webmanifest",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-background bg-hero-pattern">
      <Header />
      {children}
      <Footer />
    </main>
  );
}
