import React from "react";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/lib/utils";
import { Header } from "@/shared/components/";

const jost = Jost({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Smoky Moon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={cn(jost.className, "bg-background bg-hero-pattern")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
